//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Scripts/Input/InputContext.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/Input/InputContext.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @InputContext: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @InputContext()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""InputContext"",
    ""maps"": [
        {
            ""name"": ""BattlePlayerController"",
            ""id"": ""46a00151-9526-4e07-9e21-4f25ecf86064"",
            ""actions"": [
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""42e83d1e-0959-414e-a1d9-2c4aa2692969"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5cfc4f2f-02cd-4348-8dcd-9e0b86c266bf"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42f5fdee-e75a-4778-8bb1-3108a4a81990"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MapPlayerController"",
            ""id"": ""50ab8fee-066c-4860-8728-6561de492d49"",
            ""actions"": [
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""a30e6683-15a1-483a-9136-70ddf8d36f78"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ScaleZoom"",
                    ""type"": ""Button"",
                    ""id"": ""86a74105-f0fe-43a0-ab48-29e9f2865e93"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""64339bb6-8e97-49dc-a087-5123137f1f57"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e4dac119-deed-4194-a616-c72b78a931b2"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""PC"",
                    ""id"": ""b3888082-ef87-4073-a482-2242f180fb0f"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScaleZoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""282b2482-88f0-4fe7-9bb1-cb176334926a"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScaleZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""cd053989-8ee8-43f6-a199-10f1823bc039"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScaleZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // BattlePlayerController
        m_BattlePlayerController = asset.FindActionMap("BattlePlayerController", throwIfNotFound: true);
        m_BattlePlayerController_Click = m_BattlePlayerController.FindAction("Click", throwIfNotFound: true);
        // MapPlayerController
        m_MapPlayerController = asset.FindActionMap("MapPlayerController", throwIfNotFound: true);
        m_MapPlayerController_Click = m_MapPlayerController.FindAction("Click", throwIfNotFound: true);
        m_MapPlayerController_ScaleZoom = m_MapPlayerController.FindAction("ScaleZoom", throwIfNotFound: true);
    }

    ~@InputContext()
    {
        UnityEngine.Debug.Assert(!m_BattlePlayerController.enabled, "This will cause a leak and performance issues, InputContext.BattlePlayerController.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_MapPlayerController.enabled, "This will cause a leak and performance issues, InputContext.MapPlayerController.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // BattlePlayerController
    private readonly InputActionMap m_BattlePlayerController;
    private List<IBattlePlayerControllerActions> m_BattlePlayerControllerActionsCallbackInterfaces = new List<IBattlePlayerControllerActions>();
    private readonly InputAction m_BattlePlayerController_Click;
    /// <summary>
    /// Provides access to input actions defined in input action map "BattlePlayerController".
    /// </summary>
    public struct BattlePlayerControllerActions
    {
        private @InputContext m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public BattlePlayerControllerActions(@InputContext wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "BattlePlayerController/Click".
        /// </summary>
        public InputAction @Click => m_Wrapper.m_BattlePlayerController_Click;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_BattlePlayerController; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="BattlePlayerControllerActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(BattlePlayerControllerActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="BattlePlayerControllerActions" />
        public void AddCallbacks(IBattlePlayerControllerActions instance)
        {
            if (instance == null || m_Wrapper.m_BattlePlayerControllerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BattlePlayerControllerActionsCallbackInterfaces.Add(instance);
            @Click.started += instance.OnClick;
            @Click.performed += instance.OnClick;
            @Click.canceled += instance.OnClick;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="BattlePlayerControllerActions" />
        private void UnregisterCallbacks(IBattlePlayerControllerActions instance)
        {
            @Click.started -= instance.OnClick;
            @Click.performed -= instance.OnClick;
            @Click.canceled -= instance.OnClick;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="BattlePlayerControllerActions.UnregisterCallbacks(IBattlePlayerControllerActions)" />.
        /// </summary>
        /// <seealso cref="BattlePlayerControllerActions.UnregisterCallbacks(IBattlePlayerControllerActions)" />
        public void RemoveCallbacks(IBattlePlayerControllerActions instance)
        {
            if (m_Wrapper.m_BattlePlayerControllerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="BattlePlayerControllerActions.AddCallbacks(IBattlePlayerControllerActions)" />
        /// <seealso cref="BattlePlayerControllerActions.RemoveCallbacks(IBattlePlayerControllerActions)" />
        /// <seealso cref="BattlePlayerControllerActions.UnregisterCallbacks(IBattlePlayerControllerActions)" />
        public void SetCallbacks(IBattlePlayerControllerActions instance)
        {
            foreach (var item in m_Wrapper.m_BattlePlayerControllerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BattlePlayerControllerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="BattlePlayerControllerActions" /> instance referencing this action map.
    /// </summary>
    public BattlePlayerControllerActions @BattlePlayerController => new BattlePlayerControllerActions(this);

    // MapPlayerController
    private readonly InputActionMap m_MapPlayerController;
    private List<IMapPlayerControllerActions> m_MapPlayerControllerActionsCallbackInterfaces = new List<IMapPlayerControllerActions>();
    private readonly InputAction m_MapPlayerController_Click;
    private readonly InputAction m_MapPlayerController_ScaleZoom;
    /// <summary>
    /// Provides access to input actions defined in input action map "MapPlayerController".
    /// </summary>
    public struct MapPlayerControllerActions
    {
        private @InputContext m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public MapPlayerControllerActions(@InputContext wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "MapPlayerController/Click".
        /// </summary>
        public InputAction @Click => m_Wrapper.m_MapPlayerController_Click;
        /// <summary>
        /// Provides access to the underlying input action "MapPlayerController/ScaleZoom".
        /// </summary>
        public InputAction @ScaleZoom => m_Wrapper.m_MapPlayerController_ScaleZoom;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_MapPlayerController; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="MapPlayerControllerActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(MapPlayerControllerActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="MapPlayerControllerActions" />
        public void AddCallbacks(IMapPlayerControllerActions instance)
        {
            if (instance == null || m_Wrapper.m_MapPlayerControllerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MapPlayerControllerActionsCallbackInterfaces.Add(instance);
            @Click.started += instance.OnClick;
            @Click.performed += instance.OnClick;
            @Click.canceled += instance.OnClick;
            @ScaleZoom.started += instance.OnScaleZoom;
            @ScaleZoom.performed += instance.OnScaleZoom;
            @ScaleZoom.canceled += instance.OnScaleZoom;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="MapPlayerControllerActions" />
        private void UnregisterCallbacks(IMapPlayerControllerActions instance)
        {
            @Click.started -= instance.OnClick;
            @Click.performed -= instance.OnClick;
            @Click.canceled -= instance.OnClick;
            @ScaleZoom.started -= instance.OnScaleZoom;
            @ScaleZoom.performed -= instance.OnScaleZoom;
            @ScaleZoom.canceled -= instance.OnScaleZoom;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="MapPlayerControllerActions.UnregisterCallbacks(IMapPlayerControllerActions)" />.
        /// </summary>
        /// <seealso cref="MapPlayerControllerActions.UnregisterCallbacks(IMapPlayerControllerActions)" />
        public void RemoveCallbacks(IMapPlayerControllerActions instance)
        {
            if (m_Wrapper.m_MapPlayerControllerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="MapPlayerControllerActions.AddCallbacks(IMapPlayerControllerActions)" />
        /// <seealso cref="MapPlayerControllerActions.RemoveCallbacks(IMapPlayerControllerActions)" />
        /// <seealso cref="MapPlayerControllerActions.UnregisterCallbacks(IMapPlayerControllerActions)" />
        public void SetCallbacks(IMapPlayerControllerActions instance)
        {
            foreach (var item in m_Wrapper.m_MapPlayerControllerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MapPlayerControllerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="MapPlayerControllerActions" /> instance referencing this action map.
    /// </summary>
    public MapPlayerControllerActions @MapPlayerController => new MapPlayerControllerActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "BattlePlayerController" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="BattlePlayerControllerActions.AddCallbacks(IBattlePlayerControllerActions)" />
    /// <seealso cref="BattlePlayerControllerActions.RemoveCallbacks(IBattlePlayerControllerActions)" />
    public interface IBattlePlayerControllerActions
    {
        /// <summary>
        /// Method invoked when associated input action "Click" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnClick(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "MapPlayerController" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="MapPlayerControllerActions.AddCallbacks(IMapPlayerControllerActions)" />
    /// <seealso cref="MapPlayerControllerActions.RemoveCallbacks(IMapPlayerControllerActions)" />
    public interface IMapPlayerControllerActions
    {
        /// <summary>
        /// Method invoked when associated input action "Click" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnClick(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ScaleZoom" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnScaleZoom(InputAction.CallbackContext context);
    }
}
